### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by TheKeymaster** [findologic/dokuwiki-plugin-findologic-xml-export#3]
_From @TheKeymaster on August 4, 2017 9:28_

Add more tests.

_Copied from original issue: TheKeymaster/phpdokuwiki2findologic#3_

**Comment by TheKeymaster** [comment]
In test delete and create pages with the DokuWiki functions in order to test all corner cases (0,1,2,...).

**Comment by TheKeymaster** [comment]
Maybe make a Helper class if there is not a single function for this case.

**Comment by TheKeymaster** [comment]
# Important test cases

## Test cases

 - Test case
    - Expected result

### DokuWiki general tests

- **DokuWiki has no pages**
  -  XML should be valid.
- **DokuWiki has one page**
  - XML should be valid and one page should be exported.
- **DokuWiki has two or more pages**
  - XML should be valid and two or more pages should be exported.

### DokuWiki general page tests

- **DokuWiki page has title `test123`**
  - XML name of element should be **`test123`**.
- **DokuWiki page content is `==== test123 ==== This page is for test purposes.`**
  - XML summary and description should be **`test123 This page is for test purposes.`**.
- **DokuWiki page has no price**
  - XML price should be **`0`**.
- **DokuWiki page namespace is `test123:test123:test123`**
  - XML ordernumber should be **`test123:test123:test123`**.
  - XML url should be correct (depends on server url).
  - XML attribute category should be **`test123_test123_test123`**
- **DokuWiki page was created `1505125689`**
  - XML dateAdded should be **`2017-09-11T10:28:09+02:00`**

### DokuWiki page corner cases

- **DokuWiki page has no title and namespace is `test123:test123:test123`**
  - XML name of element should be **`Test123 Test123 Test123`** (For this #12 is still open).
- **DokuWiki page has namespace with special characters (eg. umlauts)**
  - DokuWiki itself stemms umlauts and does not allow any special characters. I can't test this really because DokuWiki already does it by default.
- **DokuWiki page has namespace `test123:test123`**
  - XML ordernumber should be **`test123:test123`**.
  - XML attribute category should be **`test123_test123`**
- **DokuWiki page has namespace `test123`**
  - XML ordernumber should be **`test123`**.
  - XML attribute category should be **`test123`**

### Call Export

- **Params `start=1` `count=1` `total=1`**
  - InvalidArgumentExeption
- **Params `start=2` `count=1` `total=1`**
  - InvalidArgumentExeption
- **Params `start=0` `count=0` `total=1`**
  - InvalidArgumentExeption
- **Params `start=1` `count=0` `total=1`**
  - InvalidArgumentExeption
- **Params `start=0` `count=10` `total=9`**
  - InvalidArgumentExeption
- **Params `start=0` `count=-1` `total=1`**
  - InvalidArgumentExeption
- **Params `start=-1` `count=1` `total=1`**
  - InvalidArgumentExeption

### Settings

- **DokuWiki pages are `home`, `start` and `test`. Exclude pages `home, start` in the settings**
  - XML with `total=1` should be exported.
- **DokuWiki page is `home`, and `test`. Exclude pages `home` in the settings**
  - XML with `total=1` should be exported.

### Todos for testing:

- Check if a function exists that allows deleting all pages and creating a new one. Also: Declare a setup method where all pages are deleted and the pages that are being needed are also created.
  - Yes: Use it to create and delete pages.
  - No: Create functions manually and delete pages manually.
- Take a look at assertXpath from PHPUnit. Maybe it is useful.

@georgms please take a look at it. Thanks for your feedback!

**Comment by georgms** [comment]
@TheKeymaster 

* **DokuWiki has no pages**: XML should be valid and contain 0 items.
* **DokuWiki page has namespace with special characters (eg. umlauts)**: What happens when you manually try to create a namespace / page title with umlauts? If the umlauts are not saved as is there really is no need to test it.
* `start=0`, `count=10`, `total=9` (ie. `start+count>total`) should not throw an `InvalidArgumentException`, it should just return 9 items. Otherwise our export script would have to adjust `count` to exactly match `total`; instead it just keeps increasing `start` until `start-count>total` and then it stops.
* The tests for excluded pages should check which pages are exported instead of just counting the number of exported items.
* The tests for excluded pages should include excluded pages at a lower lever in the hierarchy (eg. `namespace1:namespace2:page`).

Other than that: LGTM. Feel free to start implementing.

**Comment by TheKeymaster** [comment]
@georgms 

> - **DokuWiki has no pages:** XML should be valid and contain 0 items.

- Yes totally thanks!

> - **DokuWiki page has namespace with special characters (eg. umlauts):** What happens when you manually try to create a namespace / page title with umlauts? If the umlauts are not saved as is there really is no need to test it.

- If you try to save a page with a name like `leberkäse` this would result in the namespace `leberkaese`. No need to test it.

> - `start=0`, `count=10`, `total=9` (ie. `start+count>total`) should not throw an `InvalidArgumentException`, it should just return 9 items. Otherwise our export script would have to adjust `count` to exactly match `total`; instead it just keeps increasing `start` until `start-count>total` and then it stops.

- That was my error. Thanks for that.

> - The tests for excluded pages should check which pages are exported instead of just counting the number of exported items.

:+1: yes.

> - The tests for excluded pages should include excluded pages at a lower lever in the hierarchy (eg. `namespace1:namespace2:page`).

:+1: yes.

**Comment by TheKeymaster** [comment]
PR #20 fixed this issue.
