### ISSUE TITLE
Add code coverage badge 

### ISSUE THREAD

**Issue by georgms** [findologic/dokuwiki-plugin-findologic-xml-export#34]
Add https://codecov.io/ badge

**Comment by TheKeymaster** [comment]
@georgms I have not found an article for `codecov`, but you may need to approve `codecov` as third-party application in GitHub.

**Comment by georgms** [comment]
Approved ✅

**Comment by TheKeymaster** [comment]
@georgms could you provide me a badge img link like you did in issue #35 → ![CodeClimate](https://api.codeclimate.com/v1/badges/36298427d4276db18fa6/maintainability)

**Comment by georgms** [comment]
[![codecov](https://codecov.io/gh/findologic/dokuwiki-plugin-findologic-xml-export/branch/master/graph/badge.svg)](https://codecov.io/gh/findologic/dokuwiki-plugin-findologic-xml-export)

**Comment by georgms** [comment]
Codecov currently does not work, since the plugin code is in the root of the repository but during the test it is moved to `lib/plugins` so Codecov gets confused about the paths. Take a look at https://docs.codecov.io/docs/fixing-paths

Also Codecov calculates coverage only for 2 files, where's the rest of them?
