### ISSUE TITLE
Add Code Climate badge

### ISSUE THREAD

**Issue by georgms** [findologic/dokuwiki-plugin-findologic-xml-export#35]
Add https://codeclimate.com/ badge

**Comment by TheKeymaster** [comment]
@georgms you need to [Approve Code Climate as a third-party application in GitHub](https://docs.codeclimate.com/docs/approve-code-climate-as-a-third-party-application-in-github), so I can add the badge.

**Comment by georgms** [comment]
Approved ✅

**Comment by TheKeymaster** [comment]
@georgms the code climate image link is a hash, so could you provide me the link? 
You can find it under: [Badges](https://docs.codeclimate.com/v1.0/docs/overview#badges)

**Comment by georgms** [comment]
![CodeClimate](https://api.codeclimate.com/v1/badges/36298427d4276db18fa6/maintainability)

**Comment by TheKeymaster** [comment]
@georgms thanks Grand Master :+1:
