### ISSUE TITLE
Empty page when opening the plugin from the Admin page

### ISSUE THREAD

**Issue by Padlina** [findologic/dokuwiki-plugin-findologic-xml-export#46]
The link that appear on the Admin page for the plugin Findologic bring to an empty page:
/dokuwiki/doku.php?id=start&do=admin&page=findologicxmlexport

The path /dokuwiki/lib/plugins/findologicxmlexport/ bring to a 500 internal server error. 

What is the right URL to get the XML data?

**Comment by Padlina** [comment]
This seems to be due to PHP7.0 compliance.
To make it work again the following lines must be changed in DokuwikiXMLExport.php:

`if (!defined('DOKU_INC')) {
    define('DOKU_INC', realpath(dirname(__FILE__) . '/../../') . '/');
}` 
into

`if (!defined('DOKU_INC')) {
    define('DOKU_INC', realpath(dirname(__FILE__) . '/../../../') . '/');
}`
that is, point to /dokuwiki/inc/ and not /dokuwiki/lib/inc/

**Comment by TheKeymaster** [comment]
@Padlina thank you very much for using our plugin.

The plugin has not been tested with the latest DokuWiki version yet. Also you may get a warning when using PHP 7.3 that one method has not been implemented. I will create a new release soon, where those issues should be fixed.

**Comment by TheKeymaster** [comment]
@Padlina I will create a release tomorrow in which you can get the changes for fixing your issues. The version will probably be `v1.5.0`. Updating it via the DokuWiki plugin manager will also work.
